on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:
    branches:
    - master
    - dev

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - uses: actions/setup-python@v6
    - run: npm ci
      working-directory: ./renderer
    - uses: pre-commit/action@v3.0.1
  test:
    name: Renderer Tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: npm ci
      working-directory: ./renderer
    - run: npm run make-index-files
      working-directory: ./renderer
    - run: npm run test
      working-directory: ./renderer
  native:
    name: Native Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: sudo apt-get update
    - run: sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-webengine-dev libkf6coreaddons-dev libkf6globalaccel-dev libkf6windowsystem-dev liblayershellqtinterface-dev
    - run: npm ci
      working-directory: ./renderer
    - run: npm run make-index-files
      working-directory: ./renderer
    - run: npm run build
      working-directory: ./renderer
    - run: qmake6 exiled-exchange-native.pro -o Makefile
      working-directory: ./native
    - run: make -j"$(nproc)"
      working-directory: ./native
